language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

script:
  - php code-checker/src/code-checker.php -d app
  - composer test

before_script:
  - composer install --dev
  - 'composer create-project nette/code-checker code-checker ~2.3 --no-interaction --prefer-source'

sudo: false
