language: php
php:
  - 7.1
  - 7.0
  - 5.6

script:
  - php code-checker/src/code-checker.php --short-arrays -d app
  - composer test

before_script:
  - mv app/config/config.local.neon.default app/config/config.local.neon
  # Install Nette Tester & Code Checker
  - composer install --no-interaction --dev --prefer-source
  - composer create-project nette/code-checker code-checker ^2.7 --no-interaction --prefer-source

sudo: false
